<div id="login-main">
    <div class="title">Create Account</div>
    <div class="content">
        <form method="post">
        <?php
        echo $this->getContent();

        foreach ($form as $element) {
            echo '<div class="form-row">';
            echo '<label for="', $element->getName(), '">', $element->getLabel(), '</label>';
            echo $element;
            echo '</div>';
        }
        ?>
        </form>
    </div>
</div>