<html>
<head></head>
<body>
    <form>
        <table>
            <tr>
                <td>Username:</td>
                <td><input type="text" name="login-name" value="" size="25" /></td>
            </tr>
            <tr>
                <td>Password:</td>
                <td><input type="password" name="login-password" value="" size="25" /></td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" name="login-submit" value="Login" /></td>
            </tr>
        </table>
    </form>
</body>
</html>