<div id="login-main">
    <div class="title">Sign In</div>
    <div class="content">
        <form method="post" action="login/index">
        <?php
        echo $this->getContent();

        foreach ($form as $element) {
            echo '<div class="form-row">';
            echo '<label for="', $element->getName(), '">', $element->getLabel(), '</label>';
            echo $element;
            echo '</div>';
        }
        ?>
        </form>
    </div>
    <div class="title">Need an Account?</div>
    <div class="content">
        <a href="login/create" class="button button-green">Create an Account</a>
    </div>
</div>