<ul>
    <li><a href="javascript://" ng-click="openSheet('/contact/index', $index, $event)">Contacts</a></li>
    <li><a href="javascript://" ng-click="openSheet('/lead/index', $index, $event)">Leads</a></li>
    <li><a href="javascript://" ng-click="openSheet('/project/index', $index, $event)">Projects</a></li>
    <li><a href="javascript://" ng-click="openSheet('/tasklist/index', $index, $event)">Tasks</a></li>
    <li><a href="javascript://" ng-click="openSheet('/time/index', $index, $event)">Time</a></li>
</ul>