<div class="sheet-main">
    <div class="title">Create New Organization</div>
    <div class="content">
        <p>All we need right now is the name of your organization. You will be able to add more detailed information once you connect to your organization.</p>
        <?php echo $this->getContent(); ?>
        <form method="post">
            <div class="form-row">
                <label>Owner: </label> <?php echo $displayname; ?>
            </div>
        <?php
        foreach ($form as $element) {
            echo '<div class="form-row">';
            echo '<label for="', $element->getName(), '">', $element->getLabel(), '</label>';
            echo $element;
            echo '</div>';
        }
        ?>
        <div>
            <button class="button button-green" type="submit">Create</button>
            <a href="/app/select" class="button button-blue">Cancel</a>
        </div>
        </form>
    </div>
</div>